version: '3'

services:  
  python:
    image: adriannborella/python3.9-msodbcsql13:0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
    - ./script:/home/app